version: '3'
services:
 hub:
  image: selenium/hub:4.32
  ports:
   - 4444:4444
 chromebrowser:
  image: selenium/node-chromium:4.32
  shm_size: '2gb'
  depends_on:
  - hub
  environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4   
 firefoxbrowser:
  image: selenium/node-firefox:4.32
  shm_size: '2gb'
  depends_on:
  - hub
  environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443 
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4   
 vendorportal:
  image: 7013918149/v4
  depends_on:
  - hub
  environment:
   - BROWSER=${BROWSER}
   - HOST=hub
   - THREADCOUNT=3
   - TESTXML=Vendorportal.xml  
  volumes:
   - C:\Users\madhu\AppData\Local\Docker\wsl\Docker\Framework\14Framework/output/vendor:/home/Selenium-Docker/test-output  
 flight:
  image: 7013918149/v4
  depends_on:
  - hub
  environment:
   - BROWSER=${BROWSER}
   - HOST=hub
   - THREADCOUNT=4
   - TESTXML=FlightReservation.xml  
  volumes:
   - C:\Users\madhu\AppData\Local\Docker\wsl\Docker\Framework\14Framework/output/flight:/home/Selenium-Docker/test-output    