version: '3'
services:
 hub:
  image: selenium/hub:4.32
 chrome:
  image: selenium/node-chromium:4.32
  shm_size: '2gb'
  depends_on:
  - hub
  deploy: {} 
  env_file: .env
 firefox:
  image: selenium/node-firefox:4.32
  shm_size: '2gb'
  depends_on:
  - hub
  deploy: {} 
  env_file: .env
 