version: '3'
services:
 vendorportal:
  image: 7013918149/v4
  environment:
   - BROWSER=chrome
   - HOST=hub
   - THREADCOUNT=3
   - TESTXML=Vendorportal.xml  
  volumes:
   - C:\Users\madhu\AppData\Local\Docker\wsl\Docker\Framework\15Jenkins ci cd\output\node\workspace\Docker-Compose\output\node\workspace\Docker-Compose/output/vendor:/home/Selenium-Docker/test-output  
 flight:
  image: 7013918149/v4
  environment:
   - BROWSER=chrome
   - HOST=hub
   - THREADCOUNT=4
   - TESTXML=FlightReservation.xml  
  volumes:
   -  C:\Users\madhu\AppData\Local\Docker\wsl\Docker\Framework\15Jenkins ci cd\output\node\workspace\Docker-Compose\output\node\workspace\Docker-Compose/output/flight:/home/Selenium-Docker/test-output    